### ISSUE TITLE
Error in redmine 2.2

### ISSUE THREAD

**Issue by alexeyq2** [f0y/redmine_private_wiki#25]
The fix in #20 makes the plugin incompatible with redmine 2.2. It doesn't work:

NoMethodError (undefined method `project_wiki_page_path' for #WikiController:0x91c7dd0):

I changed the code back

  #        redirect_to project_wiki_page_path(@project, @page.title)
        redirect_to project_wiki_path(@project, @page.title)

And it works with my redmine 2.2.3.stable
